/*
 * This file is generated by jOOQ.
*/
package com.an3ll.data;


import com.an3ll.data.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fleet extends SchemaImpl {

    private static final long serialVersionUID = 956914190;

    /**
     * The reference instance of <code>fleet</code>
     */
    public static final Fleet FLEET = new Fleet();

    /**
     * The table <code>fleet.users</code>.
     */
    public final Users USERS = com.an3ll.data.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Fleet() {
        super("fleet", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Users.USERS);
    }
}
