/*
 * This file is generated by jOOQ.
*/
package com.an3ll.data;


import com.an3ll.data.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in fleet
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>fleet.users</code>.
     */
    public static final Users USERS = com.an3ll.data.tables.Users.USERS;
}
